version: '3'

services:
  db-app:
    build: app
    networks:
      - proxy
    environment:
      AVAILABLE_DRS: all
      API_VERSION: all
      CLICKHOUSE_HOST: sai.snad.space
      VIRTUAL_HOST: sai.db.ztf.snad.space
      HTTPS_METHOD: noredirect
      DYNDNS_HOST: sai.db.ztf.snad.space
      LETSENCRYPT_HOST: sai.db.ztf.snad.space
      LETSENCRYPT_EMAIL: letsencrypt@snad.space
    volumes:
      - /var/run/postgresql:/var/run/postgresql
    restart: always

networks:
  proxy:
    external:
      name: proxy
