version: '3'

services:
  db-app:
    build: app
    networks:
      - proxy
      - clickhouse
    environment:
      API_VERSION: "v2:v3"
      AVAILABLE_DRS: all
      CLICKHOUSE_HOST: clickhouse
      VIRTUAL_HOST: lpc.db.ztf.snad.space
      HTTPS_METHOD: noredirect
      DYNDNS_HOST: lpc.db.ztf.snad.space
      LETSENCRYPT_HOST: lpc.db.ztf.snad.space
      LETSENCRYPT_EMAIL: letsencrypt@snad.space
    restart: always

networks:
  proxy:
    external: true
  clickhouse:
    external: true
