version: '3'

services:
  db-app:
    build: app
    networks:
      - proxy
      - clickhouse
    environment:
      AVAILABLE_DRS: "dr2:dr3:dr4:dr8:dr13"
      API_VERSION: all
      CLICKHOUSE_HOST: clickhouse
      VIRTUAL_HOST: sai.db.ztf.snad.space
      HTTPS_METHOD: noredirect
      DYNDNS_HOST: sai.db.ztf.snad.space
      LETSENCRYPT_HOST: sai.db.ztf.snad.space
      LETSENCRYPT_EMAIL: letsencrypt@snad.space
    volumes:
      - /var/run/postgresql:/var/run/postgresql
    restart: always

networks:
  proxy:
    external: true
  clickhouse:
    external: true
