version: '3'

services:
  db-app-proxy:
    build: proxy
    networks:
      - proxy
    environment:
      VIRTUAL_HOST: db.ztf.snad.space
      HTTPS_METHOD: noredirect
      DYNDNS_HOST: db.ztf.snad.space
      LETSENCRYPT_HOST: db.ztf.snad.space
      LETSENCRYPT_EMAIL: letsencrypt@snad.space
    restart: always

networks:
  proxy:
    external:
      name: proxy
