version: '3'

services:
  db-app:
    build: app
    networks:
      - proxy
    environment:
      API_VERSION: v3
      AVAILABLE_DRS: "dr3:dr4:dr8"
      CLICKHOUSE_HOST: clickhouse
      VIRTUAL_HOST: uci.db.ztf.snad.space
      HTTPS_METHOD: noredirect
      DYNDNS_HOST: uci.db.ztf.snad.space
      LETSENCRYPT_HOST: uci.db.ztf.snad.space
      LETSENCRYPT_EMAIL: letsencrypt@snad.space
    restart: always

networks:
  proxy:
    external:
      name: proxy
